[package]
name = "nrmrs"
version = "0.1.0-dev.2"
edition = "2024"
authors = ["MissGwen <missgwen0211@gmail.com>"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
