[package]
name = "nrmrs"
version = "0.1.0-dev.1"
edition = "2024"
authors = ["MissGwen <missgwen0211@gmail.com>"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
sqlite = "0.37.0"
